### ISSUE TITLE
Works with Self-Hosted Terraform Enterprise?

### ISSUE THREAD

**Issue by jritsema** [hashicorp/aws-service-catalog-engine-for-tfc#22]
Any idea if this works (has been tested) with self-hosted (in AWS) Terraform Enterprise?

**Comment by piyushchughhc** [comment]
It has indeed been tested with Terraform Enterprise.  

Please see the [Provision the Engine](https://github.com/hashicorp/aws-service-catalog-engine-for-tfc?tab=readme-ov-file#provision-the-engine) section in the README.md for Terraform Enterprise specific configuration.
